include:
  - board: nice_nano_v2
    shield: corne_left
  - board: nice_nano_v2
    shield: corne_left_nice_view
  - board: nice_nano_v2
    shield: corne_right
  - board: nice_nano_v2
    shield: corne_right_nice_view
